services:
  db:
    image: ${MARIADB_IMAGE}
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${APP_NAME}-db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/temp/db/data:/var/lib/mysql:rw
      - ./docker/temp/db/logs:/var/log/mysql:rw
    container_name: ${APP_NAME}-db
    restart: unless-stopped

  redis:
    image: ${REDIS_IMAGE}
    volumes:
      - ./docker/temp/redis/data:/data:rw
      - ./docker/temp/redis/logs:/logs:rw
    ports:
      - '6379:6379'
    depends_on:
      - db
    container_name: ${APP_NAME}-redis
    restart: unless-stopped

  pma:
    image: ${PMA_IMAGE}
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db
    container_name: ${APP_NAME}-pma
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/temp/php/logs:/var/log/php:rw
      - ../app:/var/www/html:rw
    depends_on:
      - db
    ports:
      - '9000:9000'
    container_name: ${APP_NAME}-php
    restart: unless-stopped

  nginx:
    image: ${NGINX_IMAGE}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/temp/nginx/logs:/var/log/nginx:rw
      - ../app:/var/www/html:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php
    entrypoint: ["/bin/bash", "-c", "/entrypoint.sh"]
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped

networks:
  default:
    name: ${APP_NAME}-network
